// GENERATED by tool/generate_phosphor_glyphs.py. Do not edit by hand.
import 'package:flutter/widgets.dart';

import '../keys/activity_icon_ids.dart';
import 'phosphor_glyphs.dart';

/// Resolves stored `icon_id`s to glyphs (ADR-024). The database never stores
/// glyphs, codepoints or library-specific values; replacing the icon library
/// changes only the generated files.
abstract final class ActivityIconRegistry {
  static const Map<String, IconData> _glyphs = {
    'barbell': PhosphorGlyphs.barbell,
    'book-open': PhosphorGlyphs.bookOpen,
    'briefcase': PhosphorGlyphs.briefcase,
    'person-simple-walk': PhosphorGlyphs.personSimpleWalk,
    'person-simple-run': PhosphorGlyphs.personSimpleRun,
    'bicycle': PhosphorGlyphs.bicycle,
    'swimming-pool': PhosphorGlyphs.swimmingPool,
    'flower-lotus': PhosphorGlyphs.flowerLotus,
    'users-three': PhosphorGlyphs.usersThree,
    'pencil-simple': PhosphorGlyphs.pencilSimple,
    'code': PhosphorGlyphs.code,
    'cooking-pot': PhosphorGlyphs.cookingPot,
    'translate': PhosphorGlyphs.translate,
    'graduation-cap': PhosphorGlyphs.graduationCap,
    'brain': PhosphorGlyphs.brain,
    'music-notes': PhosphorGlyphs.musicNotes,
    'guitar': PhosphorGlyphs.guitar,
    'microphone': PhosphorGlyphs.microphone,
    'paint-brush': PhosphorGlyphs.paintBrush,
    'camera': PhosphorGlyphs.camera,
    'game-controller': PhosphorGlyphs.gameController,
    'moon': PhosphorGlyphs.moon,
    'bed': PhosphorGlyphs.bed,
    'coffee': PhosphorGlyphs.coffee,
    'fork-knife': PhosphorGlyphs.forkKnife,
    'drop': PhosphorGlyphs.drop,
    'pill': PhosphorGlyphs.pill,
    'first-aid': PhosphorGlyphs.firstAid,
    'tooth': PhosphorGlyphs.tooth,
    'heart': PhosphorGlyphs.heart,
    'leaf': PhosphorGlyphs.leaf,
    'plant': PhosphorGlyphs.plant,
    'dog': PhosphorGlyphs.dog,
    'baby': PhosphorGlyphs.baby,
    'house': PhosphorGlyphs.house,
    'broom': PhosphorGlyphs.broom,
    'wrench': PhosphorGlyphs.wrench,
    'shopping-cart': PhosphorGlyphs.shoppingCart,
    'wallet': PhosphorGlyphs.wallet,
    'envelope': PhosphorGlyphs.envelope,
    'phone': PhosphorGlyphs.phone,
    'chat-circle': PhosphorGlyphs.chatCircle,
    'laptop': PhosphorGlyphs.laptop,
    'presentation-chart': PhosphorGlyphs.presentationChart,
    'notebook': PhosphorGlyphs.notebook,
    'target': PhosphorGlyphs.target,
    'lightbulb': PhosphorGlyphs.lightbulb,
    'timer': PhosphorGlyphs.timer,
    'mountains': PhosphorGlyphs.mountains,
    'basketball': PhosphorGlyphs.basketball,
    'soccer-ball': PhosphorGlyphs.soccerBall,
    'tennis-ball': PhosphorGlyphs.tennisBall,
    'yin-yang': PhosphorGlyphs.yinYang,
    'globe': PhosphorGlyphs.globe,
    'airplane': PhosphorGlyphs.airplane,
    'car': PhosphorGlyphs.car,
    'sparkle': PhosphorGlyphs.sparkle,
    'star': PhosphorGlyphs.star,
  };

  /// The glyph for [iconId], or a neutral fallback for unknown/legacy IDs.
  static IconData resolve(String iconId) =>
      _glyphs[iconId] ?? _glyphs[ActivityIconIds.fallback]!;

  static bool hasGlyph(String iconId) => _glyphs.containsKey(iconId);
}
