// GENERATED by tool/generate_phosphor_glyphs.py. Do not edit by hand.

/// Stable activity icon identifiers (ADR-024). Pure Dart so the domain can
/// validate `icon_id` without depending on Flutter or the icon library.
///
/// IDs are permanent: never rename or remove one (stored data references
/// them). Each resolves in `ActivityIconRegistry`.
abstract final class ActivityIconIds {
  static const fallback = 'sparkle';

  static const all = <String>[
    'barbell',
    'book-open',
    'briefcase',
    'person-simple-walk',
    'person-simple-run',
    'bicycle',
    'swimming-pool',
    'flower-lotus',
    'users-three',
    'pencil-simple',
    'code',
    'cooking-pot',
    'translate',
    'graduation-cap',
    'brain',
    'music-notes',
    'guitar',
    'microphone',
    'paint-brush',
    'camera',
    'game-controller',
    'moon',
    'bed',
    'coffee',
    'fork-knife',
    'drop',
    'pill',
    'first-aid',
    'tooth',
    'heart',
    'leaf',
    'plant',
    'dog',
    'baby',
    'house',
    'broom',
    'wrench',
    'shopping-cart',
    'wallet',
    'envelope',
    'phone',
    'chat-circle',
    'laptop',
    'presentation-chart',
    'notebook',
    'target',
    'lightbulb',
    'timer',
    'mountains',
    'basketball',
    'soccer-ball',
    'tennis-ball',
    'yin-yang',
    'globe',
    'airplane',
    'car',
    'sparkle',
    'star',
  ];

  static final Set<String> _set = all.toSet();

  static bool isKnown(String id) => _set.contains(id);
}
