import '../../../core/design/keys/activity_color_key.dart';
import '../../../l10n/generated/app_localizations.dart';

/// What a screen reader says for an activity icon (A25): "Walking", never
/// the stored id ("person-simple-walk"). An unknown id reads as its words.
String activityIconLabel(AppLocalizations l10n, String id) => switch (id) {
  'barbell' => l10n.activityIconBarbell,
  'book-open' => l10n.activityIconBookOpen,
  'briefcase' => l10n.activityIconBriefcase,
  'person-simple-walk' => l10n.activityIconPersonSimpleWalk,
  'person-simple-run' => l10n.activityIconPersonSimpleRun,
  'bicycle' => l10n.activityIconBicycle,
  'swimming-pool' => l10n.activityIconSwimmingPool,
  'flower-lotus' => l10n.activityIconFlowerLotus,
  'users-three' => l10n.activityIconUsersThree,
  'pencil-simple' => l10n.activityIconPencilSimple,
  'code' => l10n.activityIconCode,
  'cooking-pot' => l10n.activityIconCookingPot,
  'translate' => l10n.activityIconTranslate,
  'graduation-cap' => l10n.activityIconGraduationCap,
  'brain' => l10n.activityIconBrain,
  'music-notes' => l10n.activityIconMusicNotes,
  'guitar' => l10n.activityIconGuitar,
  'microphone' => l10n.activityIconMicrophone,
  'paint-brush' => l10n.activityIconPaintBrush,
  'camera' => l10n.activityIconCamera,
  'game-controller' => l10n.activityIconGameController,
  'moon' => l10n.activityIconMoon,
  'bed' => l10n.activityIconBed,
  'coffee' => l10n.activityIconCoffee,
  'fork-knife' => l10n.activityIconForkKnife,
  'drop' => l10n.activityIconDrop,
  'pill' => l10n.activityIconPill,
  'first-aid' => l10n.activityIconFirstAid,
  'tooth' => l10n.activityIconTooth,
  'heart' => l10n.activityIconHeart,
  'leaf' => l10n.activityIconLeaf,
  'plant' => l10n.activityIconPlant,
  'dog' => l10n.activityIconDog,
  'baby' => l10n.activityIconBaby,
  'house' => l10n.activityIconHouse,
  'broom' => l10n.activityIconBroom,
  'wrench' => l10n.activityIconWrench,
  'shopping-cart' => l10n.activityIconShoppingCart,
  'wallet' => l10n.activityIconWallet,
  'envelope' => l10n.activityIconEnvelope,
  'phone' => l10n.activityIconPhone,
  'chat-circle' => l10n.activityIconChatCircle,
  'laptop' => l10n.activityIconLaptop,
  'presentation-chart' => l10n.activityIconPresentationChart,
  'notebook' => l10n.activityIconNotebook,
  'target' => l10n.activityIconTarget,
  'lightbulb' => l10n.activityIconLightbulb,
  'timer' => l10n.activityIconTimer,
  'mountains' => l10n.activityIconMountains,
  'basketball' => l10n.activityIconBasketball,
  'soccer-ball' => l10n.activityIconSoccerBall,
  'tennis-ball' => l10n.activityIconTennisBall,
  'yin-yang' => l10n.activityIconYinYang,
  'globe' => l10n.activityIconGlobe,
  'airplane' => l10n.activityIconAirplane,
  'car' => l10n.activityIconCar,
  'sparkle' => l10n.activityIconSparkle,
  'star' => l10n.activityIconStar,
  _ => id.replaceAll('-', ' '),
};

/// What a screen reader says for an activity color (A25).
String activityColorLabel(AppLocalizations l10n, ActivityColorKey key) =>
    switch (key) {
      ActivityColorKey.sky => l10n.activityColorSky,
      ActivityColorKey.lilac => l10n.activityColorLilac,
      ActivityColorKey.rose => l10n.activityColorRose,
      ActivityColorKey.teal => l10n.activityColorTeal,
      ActivityColorKey.coral => l10n.activityColorCoral,
      ActivityColorKey.slate => l10n.activityColorSlate,
    };
