// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    activityTypes,
    activityFields,
    idxActivityFieldsTypePosition,
    activityLogs,
    idxActivityLogsDay,
    idxActivityLogsTypeDay,
    logValues,
    idxLogValuesFieldNormalized,
    trgLogValuesInsertCheck,
    trgLogValuesUpdateCheck,
    trgActivityFieldsSemanticsLocked,
    trgActivityFieldsOwnerImmutable,
    trgActivityLogsTypeImmutable,
    trgActivityTypesPublicIdImmutable,
    trgActivityFieldsPublicIdImmutable,
    trgActivityLogsPublicIdImmutable,
    appPreferences,
  ];
  late final Shape0 activityTypes = Shape0(
    source: i0.VersionedTable(
      entityName: 'activity_types',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 activityFields = Shape1(
    source: i0.VersionedTable(
      entityName: 'activity_fields',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [
        'CHECK(measurable = 0 OR field_type IN (\'number\', \'rating\', \'duration\', \'boolean\'))',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_12,
        _column_2,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxActivityFieldsTypePosition = i1.Index(
    'idx_activity_fields_type_position',
    'CREATE INDEX idx_activity_fields_type_position ON activity_fields (activity_type_id, position)',
  );
  late final Shape2 activityLogs = Shape2(
    source: i0.VersionedTable(
      entityName: 'activity_logs',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [
        'CHECK(ended_at IS NULL OR ended_at >= started_at)',
        'CHECK(duration_ms IS NULL OR ended_at IS NULL OR duration_ms <= ended_at - started_at)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_12,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxActivityLogsDay = i1.Index(
    'idx_activity_logs_day',
    'CREATE INDEX idx_activity_logs_day ON activity_logs (local_date, started_at) WHERE deleted_at IS NULL',
  );
  final i1.Index idxActivityLogsTypeDay = i1.Index(
    'idx_activity_logs_type_day',
    'CREATE INDEX idx_activity_logs_type_day ON activity_logs (activity_type_id, local_date, started_at) WHERE deleted_at IS NULL',
  );
  late final Shape3 logValues = Shape3(
    source: i0.VersionedTable(
      entityName: 'log_values',
      withoutRowId: false,
      isStrict: true,
      tableConstraints: [
        'UNIQUE(log_id, field_id)',
        'CHECK((text_value IS NOT NULL)+(number_value IS NOT NULL)+(boolean_value IS NOT NULL)+(date_value IS NOT NULL)+(time_value IS NOT NULL)+(duration_ms IS NOT NULL)+(json_value IS NOT NULL)= 1)',
        'CHECK((number_value IS NULL)=(normalized_value IS NULL))',
        'CHECK(unit_code IS NULL OR number_value IS NOT NULL)',
      ],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_21,
        _column_34,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxLogValuesFieldNormalized = i1.Index(
    'idx_log_values_field_normalized',
    'CREATE INDEX idx_log_values_field_normalized ON log_values (field_id, normalized_value)',
  );
  final i1.Trigger trgLogValuesInsertCheck = i1.Trigger(
    'CREATE TRIGGER trg_log_values_insert_check BEFORE INSERT ON log_values BEGIN SELECT RAISE (ABORT, \'log_value_field_not_in_log_type\') WHERE (SELECT activity_type_id FROM activity_fields WHERE internal_id = NEW.field_id) IS NOT (SELECT activity_type_id FROM activity_logs WHERE internal_id = NEW.log_id);SELECT RAISE (ABORT, \'log_value_column_mismatch\') WHERE NOT COALESCE((SELECT CASE f.field_type WHEN \'text\' THEN NEW.text_value IS NOT NULL WHEN \'single_select\' THEN NEW.text_value IS NOT NULL WHEN \'number\' THEN NEW.number_value IS NOT NULL AND((NEW.unit_code IS NULL)=(f.dimension IS NULL))WHEN \'rating\' THEN NEW.number_value IS NOT NULL AND NEW.unit_code IS NULL WHEN \'boolean\' THEN NEW.boolean_value IS NOT NULL WHEN \'date\' THEN NEW.date_value IS NOT NULL WHEN \'time\' THEN NEW.time_value IS NOT NULL WHEN \'duration\' THEN NEW.duration_ms IS NOT NULL WHEN \'multi_select\' THEN NEW.json_value IS NOT NULL WHEN \'repeating_group\' THEN NEW.json_value IS NOT NULL ELSE 0 END FROM activity_fields AS f WHERE f.internal_id = NEW.field_id), 0);END',
    'trg_log_values_insert_check',
  );
  final i1.Trigger trgLogValuesUpdateCheck = i1.Trigger(
    'CREATE TRIGGER trg_log_values_update_check BEFORE UPDATE ON log_values BEGIN SELECT RAISE (ABORT, \'log_value_field_not_in_log_type\') WHERE (SELECT activity_type_id FROM activity_fields WHERE internal_id = NEW.field_id) IS NOT (SELECT activity_type_id FROM activity_logs WHERE internal_id = NEW.log_id);SELECT RAISE (ABORT, \'log_value_column_mismatch\') WHERE NOT COALESCE((SELECT CASE f.field_type WHEN \'text\' THEN NEW.text_value IS NOT NULL WHEN \'single_select\' THEN NEW.text_value IS NOT NULL WHEN \'number\' THEN NEW.number_value IS NOT NULL AND((NEW.unit_code IS NULL)=(f.dimension IS NULL))WHEN \'rating\' THEN NEW.number_value IS NOT NULL AND NEW.unit_code IS NULL WHEN \'boolean\' THEN NEW.boolean_value IS NOT NULL WHEN \'date\' THEN NEW.date_value IS NOT NULL WHEN \'time\' THEN NEW.time_value IS NOT NULL WHEN \'duration\' THEN NEW.duration_ms IS NOT NULL WHEN \'multi_select\' THEN NEW.json_value IS NOT NULL WHEN \'repeating_group\' THEN NEW.json_value IS NOT NULL ELSE 0 END FROM activity_fields AS f WHERE f.internal_id = NEW.field_id), 0);END',
    'trg_log_values_update_check',
  );
  final i1.Trigger trgActivityFieldsSemanticsLocked = i1.Trigger(
    'CREATE TRIGGER trg_activity_fields_semantics_locked BEFORE UPDATE OF field_type, dimension ON activity_fields WHEN(OLD.field_type IS NOT NEW.field_type OR OLD.dimension IS NOT NEW.dimension)AND EXISTS (SELECT 1 FROM log_values WHERE field_id = OLD.internal_id) BEGIN SELECT RAISE (ABORT, \'activity_field_semantics_locked\');END',
    'trg_activity_fields_semantics_locked',
  );
  final i1.Trigger trgActivityFieldsOwnerImmutable = i1.Trigger(
    'CREATE TRIGGER trg_activity_fields_owner_immutable BEFORE UPDATE OF activity_type_id ON activity_fields WHEN OLD.activity_type_id IS NOT NEW.activity_type_id BEGIN SELECT RAISE (ABORT, \'activity_field_owner_immutable\');END',
    'trg_activity_fields_owner_immutable',
  );
  final i1.Trigger trgActivityLogsTypeImmutable = i1.Trigger(
    'CREATE TRIGGER trg_activity_logs_type_immutable BEFORE UPDATE OF activity_type_id ON activity_logs WHEN OLD.activity_type_id IS NOT NEW.activity_type_id BEGIN SELECT RAISE (ABORT, \'activity_log_type_immutable\');END',
    'trg_activity_logs_type_immutable',
  );
  final i1.Trigger trgActivityTypesPublicIdImmutable = i1.Trigger(
    'CREATE TRIGGER trg_activity_types_public_id_immutable BEFORE UPDATE OF public_id ON activity_types WHEN OLD.public_id IS NOT NEW.public_id BEGIN SELECT RAISE (ABORT, \'public_id_immutable\');END',
    'trg_activity_types_public_id_immutable',
  );
  final i1.Trigger trgActivityFieldsPublicIdImmutable = i1.Trigger(
    'CREATE TRIGGER trg_activity_fields_public_id_immutable BEFORE UPDATE OF public_id ON activity_fields WHEN OLD.public_id IS NOT NEW.public_id BEGIN SELECT RAISE (ABORT, \'public_id_immutable\');END',
    'trg_activity_fields_public_id_immutable',
  );
  final i1.Trigger trgActivityLogsPublicIdImmutable = i1.Trigger(
    'CREATE TRIGGER trg_activity_logs_public_id_immutable BEFORE UPDATE OF public_id ON activity_logs WHEN OLD.public_id IS NOT NEW.public_id BEGIN SELECT RAISE (ABORT, \'public_id_immutable\');END',
    'trg_activity_logs_public_id_immutable',
  );
  late final Shape4 appPreferences = Shape4(
    source: i0.VersionedTable(
      entityName: 'app_preferences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_35, _column_36, _column_10],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get internalId =>
      columnsByName['internal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iconId =>
      columnsByName['icon_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get colorKey =>
      columnsByName['color_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get supportsTimer =>
      columnsByName['supports_timer']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get supportsPlanning =>
      columnsByName['supports_planning']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'internal_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'public_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE CHECK (length(public_id) = 36)',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(name)) > 0)',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(icon_id) > 0)',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(color_key) > 0)',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'supports_timer',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (supports_timer IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'supports_planning',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 1 CHECK (supports_planning IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get internalId =>
      columnsByName['internal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get activityTypeId =>
      columnsByName['activity_type_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fieldType =>
      columnsByName['field_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dimension =>
      columnsByName['dimension']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get required =>
      columnsByName['required']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get measurable =>
      columnsByName['measurable']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get configJson =>
      columnsByName['config_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'activity_type_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES activity_types(internal_id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'field_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (field_type IN (\'text\', \'number\', \'boolean\', \'single_select\', \'multi_select\', \'date\', \'time\', \'duration\', \'rating\', \'repeating_group\'))',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dimension',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (dimension IS NULL OR field_type = \'number\')',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (position >= 0)',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'required',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (required IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'measurable',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (measurable IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'config_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL DEFAULT \'{}\' CHECK (json_valid(config_json))',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get internalId =>
      columnsByName['internal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get publicId =>
      columnsByName['public_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get activityTypeId =>
      columnsByName['activity_type_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tzOffsetMinutes =>
      columnsByName['tz_offset_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localDate =>
      columnsByName['local_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (duration_ms IS NULL OR duration_ms >= 0)',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tz_offset_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL CHECK (tz_offset_minutes BETWEEN -1080 AND 1080)',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (local_date GLOB \'[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]\')',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get internalId =>
      columnsByName['internal_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get logId =>
      columnsByName['log_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fieldId =>
      columnsByName['field_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get textValue =>
      columnsByName['text_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get numberValue =>
      columnsByName['number_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get unitCode =>
      columnsByName['unit_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get normalizedValue =>
      columnsByName['normalized_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get booleanValue =>
      columnsByName['boolean_value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dateValue =>
      columnsByName['date_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timeValue =>
      columnsByName['time_value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get jsonValue =>
      columnsByName['json_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'log_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES activity_logs(internal_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'field_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES activity_fields(internal_id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'text_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'number_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'unit_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<double> _column_30(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'normalized_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: '',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'boolean_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (boolean_value IS NULL OR boolean_value IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (date_value IS NULL OR date_value GLOB \'[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]\')',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (time_value IS NULL OR time_value BETWEEN 0 AND 1439)',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'json_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (json_value IS NULL OR json_valid(json_value))',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get valueJson =>
      columnsByName['value_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
