#!/usr/bin/env python3
"""Generates the Phosphor glyph constants, activity icon IDs and registry.

Usage: python3 tool/generate_phosphor_glyphs.py <path-to-@phosphor-icons/web/package>

Source: the official, MIT-licensed `@phosphor-icons/web` npm package
(currently 2.1.2). Fonts are copied from `src/regular/Phosphor.ttf` and
`src/fill/Phosphor-Fill.ttf` into `assets/fonts/phosphor/` (ADR-024).
To add an icon, append its Phosphor name to UI_ICONS or ACTIVITY_ICONS
and re-run. Activity icon IDs are permanent: never remove or rename one.
"""
import re
import sys
from pathlib import Path

UI_ICONS = [
    'plus', 'trash', 'pencil-simple', 'check', 'x', 'caret-right', 'caret-down',
    'dots-three-vertical', 'arrow-counter-clockwise', 'palette', 'dots-six-vertical',
    'lock-simple', 'warning-circle', 'clock', 'calendar-blank', 'star', 'archive', 'info',
    'sun', 'calendar-dots', 'squares-four', 'chart-line-up', 'user', 'timer', 'check-circle',
    'toggle-left', 'text-aa', 'hash', 'list-checks', 'list-bullets', 'hourglass-medium',
    'rows', 'radio-button', 'caret-left', 'circle', 'play', 'skip-forward', 'arrow-bend-up-right', 'pause', 'ruler', 'repeat', 'calendar-plus', 'arrow-right',
]
FILL_ICONS = ['sun', 'calendar-dots', 'squares-four', 'chart-line-up', 'user', 'star', 'check-circle', 'target']
ACTIVITY_ICONS = [
    'barbell', 'book-open', 'briefcase', 'person-simple-walk', 'person-simple-run', 'bicycle',
    'swimming-pool', 'flower-lotus', 'users-three', 'pencil-simple', 'code', 'cooking-pot',
    'translate', 'graduation-cap', 'brain', 'music-notes', 'guitar', 'microphone', 'paint-brush',
    'camera', 'game-controller', 'moon', 'bed', 'coffee', 'fork-knife', 'drop', 'pill',
    'first-aid', 'tooth', 'heart', 'leaf', 'plant', 'dog', 'baby', 'house', 'broom', 'wrench',
    'shopping-cart', 'wallet', 'envelope', 'phone', 'chat-circle', 'laptop', 'presentation-chart',
    'notebook', 'target', 'lightbulb', 'timer', 'mountains', 'basketball', 'soccer-ball',
    'tennis-ball', 'yin-yang', 'globe', 'airplane', 'car', 'sparkle', 'star',
]


def camel(name):
    head, *rest = name.split('-')
    return head + ''.join(part.capitalize() for part in rest)


def main(package_dir):
    css = Path(package_dir, 'src/regular/style.css').read_text()
    codepoints = dict(re.findall(r'\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)"', css))
    lib = Path('lib/core/design')

    glyphs = [
        '// GENERATED by tool/generate_phosphor_glyphs.py from @phosphor-icons/web (MIT).',
        '// Do not edit by hand. Never reference these outside lib/core/design (ADR-024).',
        "import 'package:flutter/widgets.dart';",
        '',
        '/// Phosphor glyphs (regular and fill fonts share codepoints).',
        'abstract final class PhosphorGlyphs {',
    ]
    for name in dict.fromkeys(UI_ICONS + ACTIVITY_ICONS):
        glyphs.append(f"  static const {camel(name)} = IconData(0x{codepoints[name]}, fontFamily: 'Phosphor');")
    glyphs += ['}', '', '/// Filled variants for selected states.', 'abstract final class PhosphorFillGlyphs {']
    for name in FILL_ICONS:
        glyphs.append(f"  static const {camel(name)} = IconData(0x{codepoints[name]}, fontFamily: 'PhosphorFill');")
    glyphs.append('}')
    (lib / 'icons/phosphor_glyphs.dart').write_text('\n'.join(glyphs) + '\n')

    ids = '\n'.join(f"    '{name}'," for name in ACTIVITY_ICONS)
    (lib / 'keys/activity_icon_ids.dart').write_text(f'''// GENERATED by tool/generate_phosphor_glyphs.py. Do not edit by hand.

/// Stable activity icon identifiers (ADR-024). Pure Dart so the domain can
/// validate `icon_id` without depending on Flutter or the icon library.
///
/// IDs are permanent: never rename or remove one (stored data references
/// them). Each resolves in `ActivityIconRegistry`.
abstract final class ActivityIconIds {{
  static const fallback = 'sparkle';

  static const all = <String>[
{ids}
  ];

  static final Set<String> _set = all.toSet();

  static bool isKnown(String id) => _set.contains(id);
}}
''')

    entries = '\n'.join(f"    '{name}': PhosphorGlyphs.{camel(name)}," for name in ACTIVITY_ICONS)
    (lib / 'icons/activity_icon_registry.dart').write_text(f'''// GENERATED by tool/generate_phosphor_glyphs.py. Do not edit by hand.
import 'package:flutter/widgets.dart';

import '../keys/activity_icon_ids.dart';
import 'phosphor_glyphs.dart';

/// Resolves stored `icon_id`s to glyphs (ADR-024). The database never stores
/// glyphs, codepoints or library-specific values; replacing the icon library
/// changes only the generated files.
abstract final class ActivityIconRegistry {{
  static const Map<String, IconData> _glyphs = {{
{entries}
  }};

  /// The glyph for [iconId], or a neutral fallback for unknown/legacy IDs.
  static IconData resolve(String iconId) =>
      _glyphs[iconId] ?? _glyphs[ActivityIconIds.fallback]!;

  static bool hasGlyph(String iconId) => _glyphs.containsKey(iconId);
}}
''')


if __name__ == '__main__':
    main(sys.argv[1])
